sudo: false

dist: xenial

language: python

python:
  - "3.6"

install:
  - pip install -r requirements/local.txt

script:
  - python manage.py makemigrations --check --dry-run -v2
  - make lint
  - make test

before_deploy:
  # Decrypt secrets
  - openssl aes-256-cbc -K $encrypted_f4add0473100_key -iv $encrypted_f4add0473100_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  # Enable ssh agent and add ssh key to use for deployment
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 0600 dev-deployment2
  - ssh-add dev-deployment2
  - ssh-add -l
  # Install Ansible
  - pip install ansible
  # Deploy to Dev
  - git clone https://github.com/etcaterva/deployment.git eas-deployment
  - mv vault-pass eas-deployment/vault-pass
  - export ANSIBLE_HOST_KEY_CHECKING=False

deploy:
  provider: script
  script: cd eas-deployment &&  ansible-playbook -i environments/dev/hosts config-eas3.yml --vault-password-file=vault-pass --extra-vars "ansible_user=automation"
  on:
    branch: master
