sudo: false

before_install:
  - pip install --quiet coveralls
  - pip install codecov

language: python

python:
  - "3.6"

install:
  - pip install -r requirements/test.txt

script:
  - python manage.py makemigrations
  - coverage run manage.py test
  - coverage report

  - pylint eas

after_success:
  - coveralls
