#https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/

FROM python:3.7-slim
ENV PYTHONUNBUFFERED 1

# Create a group and user to run our app
ARG APP_USER=appuser
RUN groupadd -r ${APP_USER} && useradd --no-log-init -r -g ${APP_USER} ${APP_USER}

# Install packages needed to run your application (not build deps):
#   mime-support -- for mime types when serving static files
#   postgresql-client -- for running database commands
# We need to recreate the /usr/share/man/man{1..8} directories first because
# they were clobbered by a parent image.
RUN set -ex \
    && RUN_DEPS=" \
    libpcre3 \
    mime-support \
    postgresql-client \
    " \
    && apt-get update && apt-get install -y --no-install-recommends $RUN_DEPS \
    && rm -rf /var/lib/apt/lists/*

# Copy in your requirements file
ADD requirements /requirements

# Install build deps, then run `pip install`, then remove unneeded build deps all in a single step.
RUN set -ex \
    && pip install --no-cache-dir -r /requirements/prod.txt \
    \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $BUILD_DEPS \
    && rm -rf /var/lib/apt/lists/*

# Copy your application code to the container
RUN mkdir /code/
WORKDIR /code/
ADD . /code/

# uWSGI will listen on this port
EXPOSE 8000

# Env variables needed by Django or your settings
ARG EAS_SETTINGS_MODULE=eas.settings.prod
ENV DJANGO_SETTINGS_MODULE=${EAS_SETTINGS_MODULE}

ARG EAS_SENTRY_DSN
ENV SENTRY_DSN=${EAS_SENTRY_DSN}
ENV ECHALOASUERTE_LOGS_PATH=/logs


# Tell uWSGI where to find your wsgi file (change this):
ENV UWSGI_WSGI_FILE=eas/wsgi.py

# Base uWSGI configuration (you shouldn't need to change these):
ENV UWSGI_HTTP=:8000 UWSGI_MASTER=1 UWSGI_HTTP_AUTO_CHUNKED=1 UWSGI_HTTP_KEEPALIVE=1 UWSGI_LAZY_APPS=1 UWSGI_WSGI_ENV_BEHAVIOR=holy

# Number of uWSGI workers and threads per worker (customize as needed):
ENV UWSGI_WORKERS=2 UWSGI_THREADS=4
RUN apt-get update && apt-get install -y uwsgi
# Change to a non-root user
USER ${APP_USER}:${APP_USER}

#ENTRYPOINT ["/code/docker-entrypoint.sh"]

# Start uWSGI
CMD ["uwsgi", "--show-config"]
