# Generated by Django 2.0.6 on 2018-07-03 20:33

import api.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDraw',
            fields=[
                ('id', models.CharField(default=api.models.create_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('private_id', models.CharField(default=api.models.create_id, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RandomNumber',
            fields=[
                ('basedraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseDraw')),
                ('range_min', models.IntegerField()),
                ('range_max', models.IntegerField()),
            ],
            bases=('api.basedraw',),
        ),
        migrations.AddField(
            model_name='result',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.BaseDraw'),
        ),
    ]
