# Generated by Django 2.0.6 on 2018-08-09 13:07

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models

import eas.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseDraw",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "private_id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ClientDrawMetaData",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("facebook_id", models.CharField(max_length=100, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("url", models.URLField(null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", jsonfield.fields.JSONField(null=True)),
                ("schedule_date", models.DateTimeField(null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("api.basedraw",),
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
                ("number_of_groups", models.PositiveIntegerField()),
            ],
            options={"abstract": False,},
            bases=("api.basedraw", eas.api.models.ParticipantsMixin),
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
                ("number_of_results", models.PositiveIntegerField(default=1)),
                ("allow_repeated_results", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
            bases=("api.basedraw", models.Model),
        ),
        migrations.CreateModel(
            name="Lottery",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("api.basedraw", eas.api.models.ParticipantsMixin),
        ),
        migrations.CreateModel(
            name="Raffle",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=(
                "api.basedraw",
                eas.api.models.PrizesMixin,
                eas.api.models.ParticipantsMixin,
            ),
        ),
        migrations.CreateModel(
            name="RandomNumber",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
                ("number_of_results", models.PositiveIntegerField(default=1)),
                ("allow_repeated_results", models.BooleanField(default=True)),
                ("range_min", models.IntegerField()),
                ("range_max", models.IntegerField()),
            ],
            options={"abstract": False,},
            bases=("api.basedraw", models.Model),
        ),
        migrations.CreateModel(
            name="Spinner",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("api.basedraw",),
        ),
        migrations.AddField(
            model_name="result",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="api.BaseDraw",
            ),
        ),
        migrations.AddField(
            model_name="prize",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.BaseDraw"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.BaseDraw"
            ),
        ),
        migrations.AddField(
            model_name="clientdrawmetadata",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="api.BaseDraw",
            ),
        ),
    ]
