# Generated by Django 2.2.13 on 2020-11-08 21:33

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_lottery_number_of_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
                ("items_set1", jsonfield.fields.JSONField(null=True)),
                ("items_set2", jsonfield.fields.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("api.basedraw",),
        ),
    ]
