# Generated by Django 2.2.13 on 2020-12-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20201211_1322"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together=set(),
        ),
    ]
