# Generated by Django 2.2.13 on 2021-02-08 10:07

import django.db.models.deletion
from django.db import migrations, models

import eas.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_secretsantaresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("payed", models.BooleanField(default=False)),
                ("draw_url", models.URLField()),
                ("paypal_id", models.CharField(db_index=True, max_length=500)),
                ("option_certified", models.BooleanField(default=False)),
                ("option_support", models.BooleanField(default=False)),
                ("option_adfree", models.BooleanField(default=False)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_payments",
                        to="api.BaseDraw",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
