# Generated by Django 2.2.13 on 2021-02-13 07:21

import django.db.models.deletion
from django.db import migrations, models

import eas.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.BaseDraw",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("api.basedraw", eas.api.models.ParticipantsMixin),
        ),
    ]
