# Generated by Django 3.2.15 on 2022-09-03 15:35

import django.db.models.deletion
from django.db import migrations, models

import eas.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_tournament"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instagram",
            fields=[
                (
                    "basedraw_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basedraw",
                    ),
                ),
                ("post_url", models.URLField()),
                ("use_likes", models.BooleanField(default=False)),
                ("use_comments", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=(eas.api.models.PrizesMixin, "api.basedraw"),
        ),
    ]
