# Generated by Django 4.1 on 2022-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_instagram"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagram",
            name="min_mentions",
            field=models.IntegerField(default=0),
        ),
    ]
