# Generated by Django 4.1 on 2022-10-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_instagram_min_mentions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instagram",
            name="use_comments",
        ),
    ]
