# Generated by Django 4.1.4 on 2022-12-30 18:37

from django.db import migrations, models

import eas.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_shifts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eas.api.models.create_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        default=eas.api.models.created_discount_code,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="draw_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paypal_id",
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
