# Generated by Django 4.1.6 on 2023-11-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_promocode_alter_payment_draw_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretsantaresult",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
