# Generated by Django 4.1.6 on 2023-12-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_secretsantaresult_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randomnumber",
            name="range_max",
            field=models.PositiveBigIntegerField(),
        ),
    ]
