# Generated by Django 4.2.16 on 2025-03-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_payment_secret_santa_alter_payment_draw"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="revolut_id",
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
