# Generated by Django 4.2.16 on 2025-09-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_userprofile_logintoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="stripe_subscription_id",
        ),
    ]
