# Generated by Django 4.2.16 on 2025-09-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_userprofile_stripe_subscription_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="stripe_customer_id",
        ),
    ]
