# Generated by Django 4.2.16 on 2025-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="logintoken",
            name="return_url",
            field=models.URLField(
                blank=True, help_text="URL to redirect to after login", null=True
            ),
        ),
    ]
