# Generated by Django 2.2.13 on 2020-12-29 09:46

from django.db import migrations


def drop_like_indexes(apps, schema_editor):
    for index_name in [
        "api_basedraw_id_37f50f9d_like",
        "api_basedraw_private_id_7aa609cc_like",
        "api_clientdrawmetadata_draw_id_67bb108b_like",
        "api_clientdrawmetadata_id_1d0451e7_like",
        "api_coin_basedraw_ptr_id_658e6a29_like",
        "api_groups_basedraw_ptr_id_18e623d4_like",
        "api_letter_basedraw_ptr_id_539b550e_like",
        "api_link_basedraw_ptr_id_d2172227_like",
        "api_lottery_basedraw_ptr_id_46e2e50b_like",
        "api_participant_draw_id_7ac22994_like",
        "api_participant_id_cb12634b_like",
        "api_prize_draw_id_db62fcb7_like",
        "api_prize_id_6f62538f_like",
        "api_raffle_basedraw_ptr_id_657f2b6b_like",
        "api_randomnumber_basedraw_ptr_id_c1b20898_like",
        "api_result_draw_id_a0013e07_like",
        "api_result_id_326abf54_like",
        "api_spinner_basedraw_ptr_id_e27284c8_like",
    ]:
        try:
            schema_editor.execute(f"DROP INDEX {index_name};")
        except Exception as e:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20201227_1701"),
    ]

    operations = [migrations.RunPython(drop_like_indexes)]
