# Generated by Django 2.0.6 on 2018-07-01 20:42

import django.db.models.deletion
from django.db import migrations, models

import ws.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDraw',
            fields=[
                ('id', models.CharField(default=ws.models.create_id, editable=False,
                                        max_length=64, primary_key=True,
                                        serialize=False)),
                ('private_id',
                 models.CharField(default=ws.models.create_id, editable=False,
                                  max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RandomNumberResult',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RandomNumber',
            fields=[
                ('basedraw_ptr', models.OneToOneField(auto_created=True,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      parent_link=True, primary_key=True,
                                                      serialize=False, to='ws.BaseDraw')),
                ('range_min', models.IntegerField()),
                ('range_max', models.IntegerField()),
            ],
            bases=('ws.basedraw',),
        ),
        migrations.AddField(
            model_name='randomnumberresult',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='results', to='ws.BaseDraw'),
        ),
    ]
