swagger: "2.0"
info:
  description: "API definition for EAS web services"
  version: "1.0.0"
  title: "Echalo A Suerte"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "mariocj89@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api/v1"
tags:
- name: "draw"
  description: "Draw Creation and manipulation"
schemes:
- "http"
paths:
  /random_number:
    post:
      tags:
      - "draw"
      summary: "Creates a new draw"
      description: "Creates a new draw of type random_number"
      operationId: "create_random_number"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Draw object to create"
        required: true
        schema:
          $ref: "#/definitions/RandomNumber"
      responses:
        405:
          description: "Invalid input"
        200:
          description: "Result draw"
          schema:
            $ref: "#/definitions/RandomNumber"
  /random_number/{id_}:
    get:
      tags:
      - "draw"
      summary: "Find draw by private or public id"
      description: "Returns a single draw"
      operationId: "get_random_number"
      produces:
      - "application/json"
      parameters:
      - name: "id_"
        in: "path"
        description: "ID of draw to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RandomNumber"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Draw not found"
  /random_number/{id_}/toss:
    post:
      tags:
      - "draw"
      summary: "Generates a result for an existing Draw"
      description: ""
      operationId: "toss_random_number"
      parameters:
      - name: "id_"
        in: "path"
        description: "ID of draw to toss"
        required: true
        type: "string"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RandomNumber"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Draw not found"
        405:
          description: "Validation exception"
definitions:
    RandomNumber:
      type: "object"
      properties:
        metadata:
          $ref: "#/definitions/RandomNumberResult"
        id:
          type: "string"
        private_id:
          type: "string"
        created_at:
          type: "string"
        updated_at:
          type: "string"
        title:
          type: "string"
        description:
          type: "string"
        range_min:
          type: "integer"
        range_max:
          type: "integer"
        results:
          type: "array"
          items:
            $ref: "#/definitions/RandomNumberResult"
    RandomNumberResult:
      type: "object"
      properties:
        created_at:
          type: "string"
        value:
          type: "integer"
