name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 5' # Fridays at 8am

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements/local.txt

    - name: Check makemigrations
      run: |
        python manage.py makemigrations --check --dry-run -v2

    - name: Lint code
      run: |
        make lint

    - name: Run tests
      run: |
        make test
      env:
        EAS_PAYPAL_SECRET: ${{ secrets.EAS_PAYPAL_SECRET }}

    - name: Check pip frozen reqs
      run: |
        make check-frozen-reqs


  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )"
        id: extract_branch

      - name: Invoke deployment workflow
        uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
        with:
          workflow: Manually triggered workflow for deployment
          repo: etcaterva/deployment
          token: ${{ secrets.AUTOMATION_TOKEN }}
          inputs: '{ "tags": "cd-backend" }'

      - name: Deployment URL
        id: set_vars
        run: |
          echo "Follow deployment jobs for this branch:"
          echo "- https://github.com/etcaterva/deployment/actions?query=workflow%3A%22Manually+triggered+workflow+for+deployment%22+branch%3A${{ steps.extract_branch.outputs.branch }}"
